apiVersion: v1
kind: Service
metadata:
  name: argo-svc
  namespace: kubeflow
  labels:
    app: argo-ui
spec:
  ports:
  - port: 8001
    protocol: TCP
    name: argo-ui
  externalIPs:
  - <External Host IP>
  selector:
    app: tf-hub