apiVersion: v1
kind: Pod
metadata:
  name: kfcentospod
  namespace: demo-kf
spec:
  containers:
  - name: mycontainer
    imagePullPolicy: Always
    image: centos:centos7
    args:
    - sleep
    - "1000000"
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /mapr
      name: maprvolume
  volumes:
    - name: maprvolume
      persistentVolumeClaim:
        claimName: kfpvc