apiVersion: v1
kind: Service
metadata:
  name: seldon-svc
  namespace: kubeflow
  labels:
    app: grafana-prom-server
spec:
  ports:
  - port: 3000
    protocol: TCP
    name: seldon-dash
  externalIPs:
  - <External Host IP>
  selector:
    app: grafana-prom-server